# homemade example
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: local-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: local-echo
  template:
    metadata:
      labels:
        app: local-echo
    spec:
      containers:
      - name: local-echo
        image: abachman/echo-local:0.0.2
        imagePullPolicy: Never
        ports:
        - containerPort: 9999
